spring.application.name=LojaJPA


spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/lojajpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect